language: rust
rust:
  - stable
#  - beta
#  - nightly
cache: cargo
services:
  - postgresql
addons:
  postgresql: "9.6"

#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
env:
  FRONT_END_URL: "http://localhost"
  BIGNEON_DB: bigneon
  DATABASE_URL: postgres://postgres@localhost/bigneon
  TEST_DATABASE_URL: postgres://postgres:password123@localhost/bigneon_test
  TEST_DATABASE_ADMIN_URL: postgres://postgres:password123@localhost/bigneon_test
  TOKEN_SECRET: travis_secret
  TOKEN_ISSUER: bg-on-travis
  MAIL_FROM_NAME: "Big Neon Support"
  MAIL_FROM_EMAIL: "support@bigneon.com"
  MAIL_SMTP_HOST: "localhost"
  MAIL_SMTP_USER_NAME: "user"
  MAIL_SMTP_PASSWORD: "password"

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview
  - cargo install --git https://github.com/big-neon/bn-db.git --force
  - bndb_cli create -c postgres://postgres:password123@localhost/bigneon_test -e superuser@bigneon.com -p password1 -m 55555555

script:
  - cargo fmt --all -- --check
  - cargo test
