
language: rust
rust:
  - stable
#  - beta
#  - nightly
cache: cargo
services:
  - postgresql
addons:
  postgresql: "9.6"

#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
env:
  FRONT_END_URL: "http://localhost"
  BIGNEON_DB: bigneon
  DATABASE_URL: postgres://postgres:password123@localhost/bigneon
  TEST_DATABASE_URL: postgres://postgres:password123@localhost/bigneon_test
  TEST_DATABASE_ADMIN_URL: postgres://postgres:password123@localhost/bigneon_test
  TOKEN_SECRET: travis_secret
  TOKEN_ISSUER: bg-on-travis
  MAIL_FROM_NAME: "Big Neon Support"
  MAIL_FROM_EMAIL: "support@bigneon.com"
  MAIL_SMTP_HOST: "localhost"
  MAIL_SMTP_USER_NAME: "user"
  MAIL_SMTP_PASSWORD: "password"
  MAIL_SMTP_PORT: 1025
  BUILD_DIR: "api"
  STRIPE_SECRET_KEY: "sk_test_iGn9c6EJyuF3Gx0QH6uitQlb"

# matrix:
#   include:
#     - env: BUILD_DIR: "api"
#   include:
#     - env: BUILD_DIR: "db"
before_install:
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  # Workaround for invalid NPM certificate
  - npm config set strict-ssl false
  - sudo npm install -g newman

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview
  - cd db
  - scripts/init-test.sh
  - cd ..

script:
  - cargo fmt --all -- --check
  - cargo test
  - cd db
  - cargo run create -c $DATABASE_URL -f -e superuser@test.com -p password -m 8883
  - cd ../api
  - |
    cargo run &
    SERVER_PID=$!

  - newman run ../integration-tests/bigneon-tests.postman_collection.json -e ../integration-tests/travis.postman_environment.json
  - kill -s SIGTERM $SERVER_PID
