
language: rust
rust:
  - stable
#  - beta
#  - nightly
cache: cargo
services:
  - postgresql
addons:
  postgresql: "9.6"

env:
  global:
    - FRONT_END_URL="http://localhost"
    - BIGNEON_DB=bigneon

    - TEST_DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
    - TEST_DATABASE_ADMIN_URL=postgres://postgres:password123@localhost/bigneon_test
    - TOKEN_SECRET=travis_secret
    - TOKEN_ISSUER=bg-on-travis
    - MAIL_FROM_NAME="Big Neon Support"
    - MAIL_FROM_EMAIL="support@bigneon.com"
    - MAIL_SMTP_HOST="test"
    - MAIL_SMTP_USER_NAME="user"
    - MAIL_SMTP_PASSWORD="password"
    - MAIL_SMTP_PORT=1025
    - BUILD_DIR="api"
    - STRIPE_SECRET_KEY="sk_test_iGn9c6EJyuF3Gx0QH6uitQlb"
    - TARI_URL="TEST"
    - COMMUNICATION_DEFAULT_SOURCE_EMAIL="noreply@bigneon.com"
    - SENDGRID_API_KEY=" "
    - SENDGRID_TEMPLATE_BN_USER_REGISTERED="d-9ba23272db854578a5609e4e4c608f9f"
    - SENDGRID_TEMPLATE_BN_PURCHASE_COMPLETED="d-c23ba549dd0749bbb3b244b758c05dd7"




matrix:
  include:
    - name: "Test API"
      env:
       - TEST_SCRIPT="run-api-tests.sh"
       - DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
    - name: "Test Other"
      env:
      - TEST_SCRIPT="run-other-tests.sh"
      - DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
    - name: "Test Postman"
      env:
       - TEST_SCRIPT="run-integration-tests.sh"
       - DATABASE_URL=postgres://postgres:password123@localhost/bigneon_test
    - name: "Cargo Audit"
      env:
      - TEST_SCRIPT="run-cargo-audit.sh"
      - DATABASE_URL=NA
  fast_finish: true
script:
  - cd scripts
  - ./$TEST_SCRIPT

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check


before_script:

after_script:


