language: rust
rust:
  - stable
#  - beta
#  - nightly
cache: cargo
services:
  - postgresql
addons:
  postgresql: "9.6"

#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
env:
  BIGNEON_DB: bigneon
  DATABASE_URL: postgres://postgres@localhost/bigneon
  TEST_DATABASE_URL: postgres://postgres:password123@localhost/bigneon_test
  TEST_DATABASE_ADMIN_URL: postgres://postgres:password123@localhost/bigneon_test
  TOKEN_SECRET: travis_secret
  TOKEN_ISSUER: bg-on-travis
  COOKIE_SECRET_KEY: 8373b8987dab284b39c93bcda294bc294b284b72b29cd9028bca

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview
  - cargo install --git https://github.com/big-neon/bn-db.git --force
  - bndb_cli migrate -c postgres://postgres:password123@localhost/bigneon_test
 
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo test