[package]
name = "bigneon_api"
version = "0.1.0"
authors = ["CjS77"]
license = "BSD-3"
repository = "https://github.com/big-neon/bn-api/"
description = "Big Neon unified API server"
documentation = "https://github.com/big-neon/docs"

[dependencies]
actix = "0.5"
actix-web = "0.6"
diesel = { version = "1.3.0", features = ["r2d2"] }
dotenv = "0.10"
# use this one for testing with master branch
bigneon_db = { git="https://github.com/big-neon/bn-db.git" }
# use this one when testing locally.
# bigneon_db = { path = "../bn-db" }
lettre = "0.8"
lettre_email = "0.8"
log = "0.4"
log4rs = "0.8.0"
url = "1.7"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
chrono = { version = "0.4.3", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
scheduled-thread-pool = "0.2.0"
jwt = "0.4.0"
rust-crypto="0.2.36"
rustc-serialize = "0.3"

[dev-dependencies]
chrono = { version = "0.4.3", features = ["serde"] }
tokio-core = "0.1"

[[test]]
name = "tests"
