[package]
name = "bigneon_api"
version = "0.1.0"
authors = ["CjS77"]
license = "BSD-3"
repository = "https://github.com/big-neon/bn-api/"
description = "Big Neon unified API server"
documentation = "https://github.com/big-neon/docs"

[dependencies]
actix = "0.5"
actix-web = "0.6"
diesel = { version = "1.3.0", features = ["r2d2"] }
dotenv = "0.10"
bigneon_db = { path = "../bn-db" }
uuid = { version = "0.6.5", features = ["serde", "v4"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
scheduled-thread-pool = "0.2.0"

[[test]]
name = "tests"
