[package]
name = "tari-client"
version = "0.1.0"
authors = ["Philip Robinson <simian@tari.com>"]

[dependencies]
reqwest = "0.9.2"
serde = "1.0.79"
serde_json = "1.0"
serde_derive = "1.0.79"
uuid = { version = "0.6", features = ["serde", "v4"] }