[package]
name = "bigneon_api"
version = "0.1.0"
authors = ["CjS77"]
license = "BSD-3"
repository = "https://github.com/big-neon/bn-api/"
description = "Big Neon unified API server"
documentation = "https://github.com/big-neon/docs"

[dependencies]
actix = "0.7"
actix-web = "0.7"
diesel = {version = "1.3",features = ["r2d2"]}
dotenv = "0.13"
bigneon_db = { path = "../db" }
futures="0.1"
http="0.1"
hyper ="0.12"
hyper-tls = "0.3"
lettre = "0.8"
lettre_email = "0.8"
log = "0.4"
log4rs = "0.8"
url = "1.7"
uuid = { version = "0.6", features = ["serde", "v4"] }
chrono = {version = "0.4",features = ["serde"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
scheduled-thread-pool = "0.2"
jwt = "0.4.0"
rust-crypto="0.2"
rustc-serialize = "0.3"
validator = "0.7.1"
validator_derive = "0.7.2"

[dev-dependencies]
chrono = {version = "0.4.4",features = ["serde"]}

[[test]]
name = "tests"
