[package]
name = "bigneon_api"
version = "0.1.0"
authors = ["CjS77"]
license = "BSD-3"
repository = "https://github.com/big-neon/bn-api/"
description = "Big Neon unified API server"
documentation = "https://github.com/big-neon/docs"

[dependencies]
actix = "0.7"
actix-web = "0.7"
bigneon_db = { path = "../db" }
chrono = {version = "0.4", features = ["serde"]}
diesel = {version = "1.3", features = ["r2d2"]}
dotenv = "0.13"
jsonwebtoken = "5"
lettre = "0.8"
lettre_email = "0.8"
log = { version = "0.4", features = ["max_level_debug"]}
logging = {path="../logging"}
reqwest="0.9"
scheduled-thread-pool = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_with = "0.2"
stripe = {path="../stripe"}
tari-client= {path="../tari-client"}
uuid = { version = "0.6", features = ["serde", "v4"] }
validator = "0.8"
validator_derive = "0.8"
